vim.keymap.set('n', '<leader>db', vim.cmd.DapToggleBreakpoint, {})
vim.keymap.set('n', '<leader>dn', vim.cmd.DapNew, {})
vim.keymap.set('n', '<leader>dt', vim.cmd.DapTerminate, {})
vim.keymap.set('n', '<leader>dor', vim.cmd.DapStepOver, {})
vim.keymap.set('n', '<leader>dot', vim.cmd.DapStepOut, {})
vim.keymap.set('n', '<leader>di', vim.cmd.DapStepInto, {})
