vim.keymap.set('n', '<leader>ui', require 'dapui'.toggle)
vim.diagnostic.config()
vim.diagnostic.config()
vim.keymap.set('n', '<leader>dc', require 'dap'.continue)
vim.keymap.set('n', '<leader>dso', require 'dap'.step_over)
vim.keymap.set('n', '<leader>dsi', require 'dap'.step_into)
vim.keymap.set('n', '<leader>dso', require 'dap'.step_out)
vim.keymap.set('n', '<leader>db', require 'dap'.toggle_breakpoint)
vim.keymap.set('n', '<leader>ds', function()
    require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end)
