[window]
opacity = 0.8
decorations = "None"
padding = { x = 5, y = 5 }
startup_mode = "Windowed"
blur = true
title = "TERMINAL"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 7

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }

[colors]
cursor = { text = "CellBackground", cursor = "#66ccff" }
