[window]
opacity = 1
decorations = "None"
padding = { x = 5, y = 5 }
startup_mode = "Windowed"
blur = true
title = "TERMINAL"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
bold = { family = "FiraCode Nerd Font", style = "Regular"}
italic = { family = "FiraCode Nerd Font", style = "Regular"}
bold_italic = { family = "FiraCode Nerd Font", style = "Regular"}
size = 8

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }

[colors]
cursor = { text = "CellBackground", cursor = "#66ccff" }
